spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: (seu email google)
    password: (sua senha cria no senha app)
    protocol: smtp
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
thymeleaf:
  enable: true

envio:
  email:
    remetente: (seuemail)
    nomeRemetente : ('SeuNome')

server:
  port: 8082
